apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laborlens
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/blueandhack/LaborLens.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: pwd-lookup
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: laborlens-secrets
    namespace: pwd-lookup
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
