apiVersion: apps/v1
kind: Deployment
metadata:
  name: laborlens-backend
  namespace: laborlens
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: laborlens-backend
  template:
    metadata:
      labels:
        app: laborlens-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/blueandhack/laborlens-backend:493602800ad8ce5533c3ccbe6073309ee6b9e0b8
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: PORT
          value: "5001"
        - name: MONGO_URI
          value: "mongodb://laborlens-mongodb:27017/pwd_cases"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: laborlens-secrets
              key: jwt-secret
        - name: ADMIN_INIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laborlens-secrets
              key: admin-init-password
---
apiVersion: v1
kind: Service
metadata:
  name: laborlens-backend
  namespace: laborlens
spec:
  selector:
    app: laborlens-backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
