apiVersion: apps/v1
kind: Deployment
metadata:
  name: laborlens-frontend
  namespace: laborlens
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: laborlens-frontend
  template:
    metadata:
      labels:
        app: laborlens-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/blueandhack/laborlens-frontend:9a0c3def1ed3767e1baf35d4d2b58438ef2e05d8
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: laborlens-frontend
  namespace: laborlens
spec:
  selector:
    app: laborlens-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
