apiVersion: apps/v1
kind: Deployment
metadata:
  name: laborlens-frontend
  namespace: laborlens
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: laborlens-frontend
  template:
    metadata:
      labels:
        app: laborlens-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/blueandhack/laborlens-frontend:c0967b04aa6396038e7febd4c3f10897f445dee1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: laborlens-frontend
  namespace: laborlens
spec:
  selector:
    app: laborlens-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
