apiVersion: apps/v1
kind: Deployment
metadata:
  name: pwd-frontend
  namespace: pwd-lookup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pwd-frontend
  template:
    metadata:
      labels:
        app: pwd-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/blueandhack/laborlens-frontend:fbe29ad47d6c05f4aa5c828708f1a72dc618b333
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pwd-frontend
  namespace: pwd-lookup
spec:
  selector:
    app: pwd-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
