apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-www-to-apex
  namespace: pwd-lookup
spec:
  redirectRegex:
    regex: "^https?://www\\.laborlens\\.fyi/(.*)"
    replacement: "https://laborlens.fyi/${1}"
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pwd-lookup-ingress
  namespace: pwd-lookup
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt-http"
spec:
  tls:
  - hosts:
    - laborlens.fyi
    secretName: laborlens-tls
  rules:
  - host: laborlens.fyi
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: pwd-backend
            port:
              number: 5001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pwd-frontend
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pwd-lookup-ingress-www
  namespace: pwd-lookup
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt-http"
    traefik.ingress.kubernetes.io/router.middlewares: pwd-lookup-redirect-www-to-apex@kubernetescrd
spec:
  tls:
  - hosts:
    - www.laborlens.fyi
    secretName: laborlens-www-tls
  rules:
  - host: www.laborlens.fyi
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pwd-frontend
            port:
              number: 80
