const mongoose = require('mongoose');

const caseSchema = new mongoose.Schema({
    CASE_NUMBER: { type: String, required: true, unique: true },
    CASE_STATUS: String,
    RECEIVED_DATE: Date,
    DETERMINATION_DATE: Date,
    PREVAIL_WAGE_DETERM_DATE: Date,
    PWD_WAGE_EXPIRATION_DATE: Date,
    EMPLOYER_LEGAL_BUSINESS_NAME: String,
    EMPLOYER_ADDRESS_1: String,
    EMPLOYER_CITY: String,
    EMPLOYER_STATE: String,
    EMPLOYER_POSTAL_CODE: String,
    EMPLOYER_PHONE: String,
    JOB_TITLE: String,
    PWD_SOC_CODE: String,
    PWD_SOC_TITLE: String,
    PWD_WAGE_RATE: Number,
    PWD_UNIT_OF_PAY: String,
    VISA_CLASS: String,
    REDETERMINATION_DATE: Date,
    CENTER_DIRECTOR_REVIEW_DATE: Date,
    WITHDRAWAL_DATE: Date,
    EMPLOYER_POC_LAST_NAME: String,
    EMPLOYER_POC_FIRST_NAME: String,
    EMPLOYER_POC_MIDDLE_NAME: String,
    EMPLOYER_POC_JOB_TITLE: String,
    EMPLOYER_POC_ADDRESS1: String,
    EMPLOYER_POC_ADDRESS2: String,
    EMPLOYER_POC_CITY: String,
    EMPLOYER_POC_STATE: String,
    EMPLOYER_POC_POSTAL_CODE: String,
    EMPLOYER_POC_COUNTRY: String,
    EMPLOYER_POC_PROVINCE: String,
    EMPLOYER_POC_PHONE: String,
    EMPLOYER_POC_PHONE_EXT: String,
    EMPLOYER_POC_EMAIL: String,
    TRADE_NAME_DBA: String,
    EMPLOYER_ADDRESS_2: String,
    EMPLOYER_COUNTRY: String,
    EMPLOYER_PROVINCE: String,
    EMPLOYER_EXTENSION: String,
    NAICS_CODE: String,
    TYPE_OF_REPRESENTATION: String,
    AGENT_ATTORNEY_LAST_NAME: String,
    AGENT_ATTORNEY_FIRST_NAME: String,
    AGENT_ATTORNEY_MIDDLE_NAME: String,
    AGENT_ATTORNEY_ADDRESS_1: String,
    AGENT_ATTORNEY_ADDRESS_2: String,
    AGENT_ATTORNEY_CITY: String,
    AGENT_ATTORNEY_STATE: String,
    AGENT_ATTORNEY_POSTAL_CODE: String,
    AGENT_ATTORNEY_COUNTRY: String,
    AGENT_ATTORNEY_PROVINCE: String,
    AGENT_ATTORNEY_PHONE: String,
    AGENT_ATTORNEY_PHONE_EXT: String,
    AGENT_ATTORNEY_EMAIL_ADDRESS: String,
    LAWFIRM_NAME_BUSINESS_NAME: String,
    COVERED_BY_ACWIA: String,
    ACWIA_INST_HIGHER_EDUCATION: String,
    ACWIA_AFFILIATED_NON_PROFIT: String,
    ACWIA_RESEARCH_ORG: String,
    ACWIA_STATUS_CHANGED: String,
    PROF_SPORTS_LEAGUE: String,
    CBA: String,
    WAGE_SOURCE_REQUESTED: String,
    SURVEY_NAME: String,
    SURVEY_PUBLICATION_DATE: Date,
    SUPERVISE_OTHER_EMP: String,
    EMP_SOC_CODES: String,
    EMP_SOC_TITLES: String,
    REQUIRED_EDUCATION_LEVEL: String,
    REQUIRED_OTHER_DEGREE: String,
    REQUIRED_EDUCATION_MAJOR: String,
    SECOND_EDUCATION: String,
    SECOND_EDUCATION_MAJOR: String,
    REQUIRED_TRAINING: String,
    REQUIRED_TRAINING_MONTHS: Number,
    REQUIRED_TRAINING_NAME: String,
    REQUIRED_EXPERIENCE: String,
    REQUIRED_EXPERIENCE_MONTHS: Number,
    REQUIRED_OCCUPATION: String,
    SPECIAL_SKILLS_REQUIREMENTS: String,
    SPEC_REQ_LICENSE_CERT: String,
    SPEC_REQ_FOREIGN_LANG: String,
    SPEC_REQ_RES_FELLOW: String,
    SPEC_REQ_OTHER: String,
    ALTERNATIVE_REQUIREMENTS: String,
    ALT_EDUCATION_LEVEL: String,
    ALT_OTHER_DEGREE: String,
    ALT_EDUCATION_MAJOR: String,
    ALT_TRAINING: String,
    ALT_TRAINING_MONTHS: Number,
    ALT_TRAINING_NAME: String,
    ALT_EXPERIENCE: String,
    ALT_EXPERIENCE_MONTHS: Number,
    ALT_SPECIAL_SKILLS: String,
    ALT_LICENSE_CERT: String,
    ALT_FOREIGN_LANGUAGE: String,
    ALT_RES_FELLOWSHIP: String,
    ALT_OTHER_REQ: String,
    SUGGESTED_SOC_CODE: String,
    SUGGESTED_SOC_TITLE: String,
    SUPERVISOR_JOB_TITLE: String,
    TRAVEL_REQUIRED: String,
    TRAVEL_DETAILS: String,
    PRIMARY_WORKSITE_ADDRESS_1: String,
    PRIMARY_WORKSITE_ADDRESS_2: String,
    PRIMARY_WORKSITE_CITY: String,
    PRIMARY_WORKSITE_STATE: String,
    PRIMARY_WORKSITE_COUNTY: String,
    PRIMARY_WORKSITE_POSTAL_CODE: String,
    OTHER_WORKSITE_LOCATION: String,
    O_NET_CODE: String,
    O_NET_TITLE: String,
    O_NET_CODE_COMBO: String,
    O_NET_TITLE_COMBO: String,
    PWD_OES_WAGE_LEVEL: String,
    PWD_WAGE_SOURCE: String,
    PWD_SURVEY_NAME: String,
    ALT_PWD_WAGE_RATE: Number,
    ALT_PWD_UNIT_OF_PAY: String,
    ALT_PWD_OES_WAGE_LEVEL: String,
    ALT_PWD_WAGE_SOURCE: String,
    ALT_PWD_SURVEY_NAME: String,
    BLS_AREA: String,
    H2B_HIGHEST_PWD: Number,
    WAGE_DET_NOTES: String,
}, { strict: false, timestamps: true });

// Text index for search functionality
caseSchema.index({
    EMPLOYER_LEGAL_BUSINESS_NAME: 'text',
    CASE_NUMBER: 'text',
    EMPLOYER_ADDRESS_1: 'text',
    EMPLOYER_CITY: 'text',
    EMPLOYER_STATE: 'text',
    JOB_TITLE: 'text'
}, {
    weights: {
        EMPLOYER_LEGAL_BUSINESS_NAME: 10,
        CASE_NUMBER: 5,
        EMPLOYER_ADDRESS_1: 2,
        JOB_TITLE: 2
    }
});

// Regular indexes for partial (regex) search performance
caseSchema.index({ EMPLOYER_LEGAL_BUSINESS_NAME: 1 });
caseSchema.index({ EMPLOYER_CITY: 1 });
caseSchema.index({ EMPLOYER_STATE: 1 });
caseSchema.index({ JOB_TITLE: 1 });
caseSchema.index({ DETERMINATION_DATE: -1 });
caseSchema.index({ RECEIVED_DATE: -1 });

// Compound index for the default sorting
caseSchema.index({ DETERMINATION_DATE: -1, EMPLOYER_LEGAL_BUSINESS_NAME: 1 });

module.exports = mongoose.model('Case', caseSchema);
